image: gradle:6.0.1-jdk8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

test:
  stage: test
  script: gradle --build-cache check assemble --stacktrace
  only:
    - master
    - develop
    - merge_requests
  cache:
    key: "$CI_PIPELINE_ID"
    policy: push
    paths:
      - build
      - .gradle

deploy:bintray:
  stage: deploy
  script: gradle release -Ppublish=true -Poverride=false -Pprod
  only:
    - master
  cache:
    key: "$CI_PIPELINE_ID"
    policy: pull
    paths:
      - build
      - .gradle
