package lt.petuska.kvdom.dom.w3c.dom

actual interface UnionElementOrHTMLCollection
actual interface UnionElementOrRadioNodeList
actual interface UnionHTMLOptGroupElementOrHTMLOptionElement
actual interface UnionAudioTrackOrTextTrackOrVideoTrack
actual interface UnionElementOrMouseEvent
actual interface RenderingContext
actual interface HTMLOrSVGImageElement : CanvasImageSource
actual interface CanvasImageSource : ImageBitmapSource
actual interface ImageBitmapSource
actual interface UnionMessagePortOrWindowProxy
actual interface HTMLOrSVGScriptElement
actual interface ElementContentEditable {
  actual var contentEditable: String
  actual val isContentEditable: Boolean
}